# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_text', models.CharField(max_length=100)),
            ],
        ),
    ]
