# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tower', '0002_auto_20170224_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articleColumn',
            new_name='article_column',
        ),
    ]
